[settings]
atomic_links = true       # swaps links via temp file for safety
auto_detect_config = true # try to match hostname to a config
on_conflict = "ask"       #  overwrite, adopt, skip, abort or ask (default: ask)

[variables]
editor = "nvim"

# scripts that run before dotsy switch
[hooks.pre]
pre_link = "echo 'pre hook'"

# scripts that run after dotsy switch
[hooks.post]
post_link = "echo 'post hook'"

# global configs that gets applied regardless of config
[global.links]
"~/.bashrc" = "bash/bashrc"
"~/.gitconfig" = "git/gitconfig"

# each config below is a collection of configs

# desktop config
[configs.desktop.links]
"~/.config/i3/config" = "linux/i3_config"
"~/.config/polybar/config" = "linux/polybar_config"

# server config
[configs.server.links]
"~/.tmux.conf" = "server/tmux.conf"

# termux config
[configs.termux.links]
"~/.termux" = "termux/.termux"
